apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: CLO835
  namespace: project
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clo835-binding
  namespace: project
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: project
roleRef:
  kind: Role
  name: CLO835
  apiGroup: rbac.authorization.k8s.io 