apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: project
type: Opaque
data:
  DB_USER: cm9vdA==  # root (base64 encoded)
  DB_PASSWORD: cGFzc3dvcmQ=  # password (base64 encoded)
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # password (base64 encoded) 